### PR TITLE
feat: add `crossorigin` attribute to legacy branch

### PR DESCRIPTION
**Pull request by myst729**
Feature requested in #14 , this PR is for v1.x.

Looks like your *legacy* branch is the same as *master* now. Please reset to tag **v1.8.1** so this could be merged.

### CODE REVIEW

**Comment by van-nguyen** [comment]
Hi @myst729 sorry it took awhile to have a look at this. The reason being is that there are some additional features after that tag, would be good if we can completely backport it. Just need to revert the v5 syntax.

**Comment by myst729** [comment]
Need to reset your **legacy** branch to [4e45592](https://github.com/van-nguyen/webpack-cdn-plugin/commit/4e455920ace7c7f4aa84f3540fe2a20059ace2af)

image

**Comment by myst729** [comment]
Well, sound a good amount of labour. 😃

**Comment by xyy94813** [comment]
Stagnation?

**Comment by myst729** [comment]
> Stagnation?

I guess so. On the other hand, I think this PR could be marked with _won't merge_. Try upgrading webpack in your project. That's a much better option AFAIK.

**Comment by myst729** [comment]
Shall we close this PR? I don't think it's worth fixing now.

**Pull request closed without merging**
