### PR TITLE
Add option to generate Subresource Integrity (SRI) for static assets

### PR DESCRIPTION
**Pull request by leibowitz**
This adds a new `sri` option that works similarly to the [`crossOrigin`](https://github.com/shirotech/webpack-cdn-plugin/#crossoriginstring-optional) one, where it alters the generated tag within the [`processTag`](https://github.com/shirotech/webpack-cdn-plugin/blob/9bb9c7c8a8521a8843d028b65d9c5d9d7f951923/module.js#L110-L112) function, to add a new attribute – in this case the [`integrity`](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)

### CODE REVIEW

**Comment by shirotech** [comment]
Nice one @leibowitz looks good to merge, but just a question on the empty catch block.

**Comment by leibowitz** [comment]
I wasn't sure what to do when an asset hash fails to be computed. Errors can occur when a resource is missing from the a cdn (404) or the cdn might be down (5xx)
With the catch the errors will silently be ignored. In hindsight that's probably not the best idea, as it would skip any problematic resource.
I could throw a new exception with a more descriptive error message, like:
```js
catch (e) {
    throw `Failed to generate hash for resource: ${url}.\nException:\n${e}`;
}
```

**Comment by leibowitz** [comment]
Also worth noting that the use of [async/await](https://v8.dev/blog/v8-release-55#async-functions) will make the plugin not work with node < 7.6
https://www.infoq.com/news/2017/02/node-76-async-await/

Not sure if this is an issue for anyone currently using this library.

**Comment by morriq** [comment]
nice one :)

**Pull request merged**
